name: "E2E Setup"
description: "Installs dependencies needed to run E2E tests"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependenciess
      shell: bash
      run: npm ci
