name: "Run Playwright"
description: "Runs Playwright E2E Tests"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/e2e-setup

    - name: Install Playwright Browsers (Chromium only)
      shell: bash
      # This line is changed to install only 'chromium'
      run: npx playwright install chromium --with-deps

    - name: Playwright run
      shell: bash
      run: npm run test:pw

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright/reports/
        retention-days: 15
